// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASHuTU1BPs76To_vCLVpUlZXK2QmlQR3g',
    appId: '1:876006086040:web:2496bf09a247472a33c7ed',
    messagingSenderId: '876006086040',
    projectId: 'flutter-chess-app-gelo-hipe',
    authDomain: 'flutter-chess-app-gelo-hipe.firebaseapp.com',
    storageBucket: 'flutter-chess-app-gelo-hipe.firebasestorage.app',
    measurementId: 'G-3EZSSJFSQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX9Y2JM6uXiDyWAij9hLZVYkFtH5ZsX4o',
    appId: '1:876006086040:android:1ad7993524e5117b33c7ed',
    messagingSenderId: '876006086040',
    projectId: 'flutter-chess-app-gelo-hipe',
    storageBucket: 'flutter-chess-app-gelo-hipe.firebasestorage.app',
  );
}
